### ISSUE TITLE
invisible output in RStudio dark themes

### ISSUE THREAD

**Issue by BTunca** [dr-JT/semoutput#1]
Hi!

Nice package! I noticed that when running the markdown file output was invisible. When I changed to a white RStudio theme it looked normal.

Would that be an easy fix?

Thanks and good job!
![screenshot_4](https://user-images.githubusercontent.com/27208030/45217572-e0c22280-b2a4-11e8-99a7-59b7b61178db.png)

**Comment by dr-JT** [comment]
This is strange. However, it seems to have more to do with RMarkdown dark themes. 

https://support.rstudio.com/hc/en-us/community/posts/220529448-knitr-kable-output-not-visible-on-dark-theme

I am using the "Material" theme and it displays correctly.

**Comment by hansero** [comment]
Maybe it's late(2 years:D) but i've a solution with same problem.You need change foreground color of your preferred theme(or change html background)

Here is you can edit your preferred theme : https://tmtheme-editor.herokuapp.com

**Comment by dr-JT** [comment]
I am closing this issue because resolving it seems to require changing theme settings in RStudio
