### ISSUE TITLE
Error: Problem with sem_factorcor() and sem_factorvar()

### ISSUE THREAD

**Issue by iron-hong** [dr-JT/semoutput#4]
Hello, thanks for your great package!

I'm currently running semoutput package for my work.
Everything went smoothly enough until after trying to analyze the latent factor correlation and residual variance.
To which I get an error that says:
> sem_factorcor(fit, factors = factors)
Error: Problem with `filter()` input `..2`.
i Input `..2` is `lhs %in% factors`.
x object 'factors' not found
Run `rlang::last_error()` to see where the error occurred.

> sem_factorvar(fit, factors = factors)
Error: Problem with `filter()` input `..2`.
i Input `..2` is `lhs %in% factors`.
x object 'factors' not found
Run `rlang::last_error()` to see where the error occurred.

What seems to be the problem?
I tried to reinstall library(semoutput) again, but the same error appears.

Thank you very much in advance.

**Comment by dr-JT** [comment]
The functions need you to specify a list c() of latent factor labels that were used in the lavaan model. Thinking of it now, I really should remove the need to do that and automatically figure out the labels of the latent factors. Though I may have had some reason for doing this.

**Comment by dr-JT** [comment]
I updated the package so that the functions no longer require the argument factors = c(). It will automatically detect the latent factor labels from the model.

**Comment by iron-hong** [comment]
Thank you so much for the quick update. I just tried the function, and it worked!
